### ISSUE TITLE
[3일차 to-do-list]

### ISSUE THREAD

**Issue by rlaehgus97** [DE32-3nd-team1/DE32-3nd-team1#15]
- [ ] airflow에서 db에 있는 이미지 경로로 이미지 읽어와서 모델 처리하고 결과를 db에 저장하는 것까지 확인
- [ ] 간이로 넣은 이미지들(test1 ~ 6.jpg)로 pyspark 돌려서 결과가 나오는지 확인
- [ ] streamlit, fastapi 연결하기
